FROM ubuntu:20.04
LABEL maintainer="Federico 'Larroca' La rocca - flarroca@fing.edu.uy"

#ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

# else it will output an error about Gtk namespace not found
RUN apt-get install -y gir1.2-gtk-3.0

# to have add-apt-repository available
RUN apt-get install -y software-properties-common

RUN add-apt-repository -y ppa:gnuradio/gnuradio-releases-3.9

# create user gnuario with sudo (and password gnuradio)
RUN apt-get install -y sudo
RUN useradd --create-home --shell /bin/bash -G sudo gnuradio
RUN echo 'gnuradio:gnuradio' | chpasswd

# I create a dir at home which I'll use to persist after the container is closed (need to change it's ownership)
RUN mkdir /home/gnuradio/persistent  && chown gnuradio /home/gnuradio/persistent

RUN apt-get update

RUN apt-get install -y gnuradio

# installing other packages needed for downloading and installing OOT modules
RUN apt-get install -y gnuradio-dev cmake git libboost-all-dev libcppunit-dev liblog4cpp5-dev python3-pygccxml pybind11-dev liborc-dev

# of course, nothing useful can be done without vim
RUN apt-get install -y vim
RUN apt-get install -y vim-gtk3

# MB FEATURES
RUN apt-get install -y rapidjson-dev swig libsndfile1-dev libuhd-dev uhd-host librtlsdr-dev rtl-sdr

# [MB Custom ENV START]

# BASHRC
RUN echo "export GRC_BLOCKS_PATH=/usr/share/gnuradio/grc/block" >> /home/gnuradio/.bashrc
RUN echo "export DISPLAY=:10.0" >> /home/gnuradio/.bashrc

RUN echo "export GRC_BLOCKS_PATH=/usr/share/gnuradio/grc/block" >> /root/.bashrc
RUN echo "export DISPLAY=:10.0" >> /root/.bashrc

# DEPENDENCIES

RUN git clone https://github.com/skysafe/gr-sigmf
RUN cd gr-sigmf && mkdir build && cd build && cmake .. && make && make install && ldconfig

RUN git clone https://github.com/osmocom/gr-osmosdr
RUN cd gr-osmosdr && mkdir build && cd build && cmake .. && make && make install && ldconfig

# [MB Custom ENV STOP]

USER gnuradio

WORKDIR /home/gnuradio

# [MB Custom ENV START]

EXPOSE 5096

# [MB Custom ENV STOP]

ENV PYTHONPATH "${PYTHONPATH}:/usr/local/lib/python3/dist-packages"

CMD bash
